  export const categoriesShopByCategories = ["JNV-Sainik-RMS", "Books-All-Competitions", "SSC-Exams", "Defence", "Railway-Exams", "CUET-Exams"]

  export const categoryBooksShopByCategories = {
    "JNV-Sainik-RMS": [
      {
        id: 1,
        author_id: 101,
        is_ebook: 0,
        stock_status: "in_stock",
        category: "JNV-Sainik-RMS",
        bestseller: 1,
        latest_release: 0,
        most_purchased: 1,
        on_sale: 1,
        exam_category: "Entrance Exam",
        location: "India",
        sku_number: "SKU1",
        isbn_number: "ISBN1",
        sequence_number: 1,
        book_url: "/jnv-guide-book",
        title: "JNV Guide Book",
        base_price: "21.0",
        discounted_price: "16.0",
        short_description: "Comprehensive guide for JNV exams.",
        images: [
          "https://radianbooks.in/Uploads/Products/jnv-guide-english-2025-min-65dedb917f3f3.webp",
        ],
        image_alt_tag: "JNV Guide Book",
        description: "A detailed preparation book for JNV exams.",
        pages: 200,
        weight: "500g",
        dimensions: "20x14x2 cm",
        binding: "Paperback",
        author: "Author 1",
        meta_title: "JNV Guide Book",
        meta_description: "Best guide for JNV entrance exam preparation.",
        canonical_tag: "/jnv-guide-book",
        created_at: "2021-01-01",
        rating: 4,
      },
      {
        id: 2,
        author_id: 102,
        is_ebook: 0,
        stock_status: "in_stock",
        category: "JNV-Sainik-RMS",
        bestseller: 0,
        latest_release: 1,
        most_purchased: 0,
        on_sale: 1,
        exam_category: "Entrance Exam",
        location: "India",
        sku_number: "SKU2",
        isbn_number: "ISBN2",
        sequence_number: 2,
        book_url: "/sainik-school-entrance",
        title: "Sainik School Entrance",
        base_price: "24.0",
        discounted_price: "18.0",
        short_description: "Complete guide for Sainik School Entrance exams.",
        images: [
          "https://radianbooks.in/Uploads/Products/jnv-guide-hindi-2025-min-65f8010e724ed.webp",
        ],
        image_alt_tag: "Sainik School Entrance",
        description: "A must-have book for Sainik School entrance preparation.",
        pages: 250,
        weight: "600g",
        dimensions: "21x15x2.5 cm",
        binding: "Paperback",
        author: "Author 2",
        meta_title: "Sainik School Entrance Guide",
        meta_description: "Best book for Sainik School exam preparation.",
        canonical_tag: "/sainik-school-entrance",
        created_at: "2021-02-01",
        rating: 5,
      },
    ],
    "Books-All-Competitions": [
      {
        id: 3,
        author_id: 103,
        is_ebook: 1,
        stock_status: "out_of_stock",
        category: "Books-All-Competitions",
        bestseller: 1,
        latest_release: 0,
        most_purchased: 1,
        on_sale: 0,
        exam_category: "General Knowledge",
        location: "India",
        sku_number: "SKU4",
        isbn_number: "ISBN4",
        sequence_number: 3,
        book_url: "/general-knowledge",
        title: "General Knowledge",
        base_price: "18.0",
        discounted_price: "12.0",
        short_description: "Enhance your general knowledge.",
        images: [
          "https://radianbooks.in/Uploads/Products/basic-mathematics-revised-2025-min-67977566723cc.webp",
        ],
        image_alt_tag: "General Knowledge Book",
        description: "An extensive guide to general knowledge.",
        pages: 150,
        weight: "400g",
        dimensions: "19x13x1.5 cm",
        binding: "Paperback",
        author: "Author 4",
        meta_title: "General Knowledge Book",
        meta_description: "Best book to improve general knowledge.",
        canonical_tag: "/general-knowledge",
        created_at: "2021-04-01",
        rating: 3,
      },
      {
        id: 4,
        author_id: 104,
        is_ebook: 0,
        stock_status: "in_stock",
        category: "Books-All-Competitions",
        bestseller: 0,
        latest_release: 1,
        most_purchased: 1,
        on_sale: 1,
        exam_category: "Aptitude",
        location: "India",
        sku_number: "SKU5",
        isbn_number: "ISBN5",
        sequence_number: 4,
        book_url: "/reasoning-skills",
        title: "Reasoning Skills",
        base_price: "20.0",
        discounted_price: "15.0",
        short_description: "Improve logical reasoning skills.",
        images: [
          "https://radianbooks.in/Uploads/Products/quantative-aptitude-min-6513b32ba556b.webp",
        ],
        image_alt_tag: "Reasoning Skills Book",
        description: "A complete guide to mastering logical reasoning.",
        pages: 180,
        weight: "450g",
        dimensions: "20x14x2 cm",
        binding: "Paperback",
        author: "Author 5",
        meta_title: "Reasoning Skills",
        meta_description: "Best book for developing reasoning skills.",
        canonical_tag: "/reasoning-skills",
        created_at: "2021-05-01",
        rating: 4,
      },
    ],
  };
  
  export const categoryBooksShopByState = {
    "UP": [
      { id: "1", name: "JNV Guide Book", images: ["https://radianbooks.in/Uploads/Products/jnv-guide-english-2025-min-65dedb917f3f3.webp"], price: 16.0, originalPrice: 21.0, discount: 25, rating: 4, sku_number: "SKU1", isbn_number: "ISBN1", title: "JNV Guide Book", base_price: 21.0, sale_price: 16.0, author: "Author 1", publisher: "Publisher 1", publication_date: "2021-01-01", pages: 200, language: "English", discounted_price: 16.0, weight: "500g", binding: "Paperback", dimensions: "20x14x2 cm" },
      { id: "2", name: "Sainik School Entrance", images: ["https://radianbooks.in/Uploads/Products/jnv-guide-hindi-2025-min-65f8010e724ed.webp"], price: 18.0, originalPrice: 24.0, discount: 30, rating: 5, sku_number: "SKU2", isbn_number: "ISBN2", title: "Sainik School Entrance", base_price: 24.0, sale_price: 18.0, author: "Author 2", publisher: "Publisher 2", publication_date: "2021-02-01", pages: 250, language: "English", discounted_price: 18.0, weight: "600g", binding: "Paperback", dimensions: "21x15x2.5 cm" },
      { id: "3", name: "RMS Preparation", images: ["https://radianbooks.in/Uploads/Products/jnv-bengali-study-guide-2025-26-min-67befebd9750e.webp"], price: 14.0, originalPrice: 19.0, discount: 20, rating: 4, sku_number: "SKU3", isbn_number: "ISBN3", title: "RMS Preparation", base_price: 19.0, sale_price: 14.0, author: "Author 3", publisher: "Publisher 3", publication_date: "2021-03-01", pages: 300, language: "English", discounted_price: 14.0, weight: "550g", binding: "Paperback", dimensions: "22x16x2 cm" },
      { id: "4", name: "RMS Preparation", images: ["https://radianbooks.in/Uploads/Products/jnv-bengali-min-66ab2033bb594.webp"], price: 14.0, originalPrice: 19.0, discount: 20, rating: 4, sku_number: "SKU3", isbn_number: "ISBN3", title: "RMS Preparation", base_price: 19.0, sale_price: 14.0, author: "Author 3", publisher: "Publisher 3", publication_date: "2021-03-01", pages: 300, language: "English", discounted_price: 14.0, weight: "550g", binding: "Paperback", dimensions: "22x16x2 cm" },
    ],
    "Haryana": [
      { id: "4", name: "General Knowledge", images: ["https://radianbooks.in/Uploads/Products/basic-mathematics-revised-2025-min-67977566723cc.webp"], price: 12.0, originalPrice: 18.0, discount: 35, rating: 3, sku_number: "SKU4", isbn_number: "ISBN4", title: "General Knowledge", base_price: 18.0, sale_price: 12.0, author: "Author 4", publisher: "Publisher 4", publication_date: "2021-04-01", pages: 150, language: "English", discounted_price: 12.0, weight: "400g", binding: "Paperback", dimensions: "19x13x1.5 cm" },
      { id: "5", name: "Reasoning Skills", images: ["https://radianbooks.in/Uploads/Products/quantative-aptitude-min-6513b32ba556b.webp"], price: 15.0, originalPrice: 20.0, discount: 25, rating: 4, sku_number: "SKU5", isbn_number: "ISBN5", title: "Reasoning Skills", base_price: 20.0, sale_price: 15.0, author: "Author 5", publisher: "Publisher 5", publication_date: "2021-05-01", pages: 180, language: "English", discounted_price: 15.0, weight: "450g", binding: "Paperback", dimensions: "20x14x2 cm" },
      { id: "6", name: "Quantitative Aptitude", images: ["https://radianbooks.in/Uploads/Products/general-intelligence-for-reasoning-2025-min-67a49a1da8c3e.webp"], price: 17.0, originalPrice: 22.0, discount: 20, rating: 5, sku_number: "SKU6", isbn_number: "ISBN6", title: "Quantitative Aptitude", base_price: 22.0, sale_price: 17.0, author: "Author 6", publisher: "Publisher 6", publication_date: "2021-06-01", pages: 220, language: "English", discounted_price: 17.0, weight: "500g", binding: "Paperback", dimensions: "21x15x2 cm" },
      { id: "7", name: "Quantitative Aptitude", images: ["https://radianbooks.in/Uploads/Products/prathmik-ankganit-min-65b4dbb6e6ac7.webp"], price: 17.0, originalPrice: 22.0, discount: 20, rating: 5, sku_number: "SKU6", isbn_number: "ISBN6", title: "Quantitative Aptitude", base_price: 22.0, sale_price: 17.0, author: "Author 6", publisher: "Publisher 6", publication_date: "2021-06-01", pages: 220, language: "English", discounted_price: 17.0, weight: "500g", binding: "Paperback", dimensions: "21x15x2 cm" },
    ],
  }
  export const categoryBooksShopByStateArray = [
    {
      "UP": [
        {
          id: "1",
          name: "JNV Guide Book",
          images: ["https://radianbooks.in/Uploads/Products/jnv-guide-english-2025-min-65dedb917f3f3.webp"],
          price: 16.0,
          originalPrice: 21.0,
          discount: 25,
          rating: 4,
          sku_number: "SKU1",
          isbn_number: "ISBN1",
          title: "JNV Guide Book",
          base_price: 21.0,
          sale_price: 16.0,
          author: "Author 1",
          publisher: "Publisher 1",
          publication_date: "2021-01-01",
          pages: 200,
          language: "English",
          discounted_price: 16.0,
          weight: "500g",
          binding: "Paperback",
          dimensions: "20x14x2 cm",
        },
        {
          id: "2",
          name: "Sainik School Entrance",
          images: ["https://radianbooks.in/Uploads/Products/jnv-guide-hindi-2025-min-65f8010e724ed.webp"],
          price: 18.0,
          originalPrice: 24.0,
          discount: 30,
          rating: 5,
          sku_number: "SKU2",
          isbn_number: "ISBN2",
          title: "Sainik School Entrance",
          base_price: 24.0,
          sale_price: 18.0,
          author: "Author 2",
          publisher: "Publisher 2",
          publication_date: "2021-02-01",
          pages: 250,
          language: "English",
          discounted_price: 18.0,
          weight: "600g",
          binding: "Paperback",
          dimensions: "21x15x2.5 cm",
        },
        {
          id: "3",
          name: "RMS Preparation",
          images: ["https://radianbooks.in/Uploads/Products/jnv-bengali-study-guide-2025-26-min-67befebd9750e.webp"],
          price: 14.0,
          originalPrice: 19.0,
          discount: 20,
          rating: 4,
          sku_number: "SKU3",
          isbn_number: "ISBN3",
          title: "RMS Preparation",
          base_price: 19.0,
          sale_price: 14.0,
          author: "Author 3",
          publisher: "Publisher 3",
          publication_date: "2021-03-01",
          pages: 300,
          language: "English",
          discounted_price: 14.0,
          weight: "550g",
          binding: "Paperback",
          dimensions: "22x16x2 cm",
        }
      ]
    },
    {
      "Haryana": [
        {
          id: "4",
          name: "General Knowledge",
          images: ["https://radianbooks.in/Uploads/Products/basic-mathematics-revised-2025-min-67977566723cc.webp"],
          price: 12.0,
          originalPrice: 18.0,
          discount: 35,
          rating: 3,
          sku_number: "SKU4",
          isbn_number: "ISBN4",
          title: "General Knowledge",
          base_price: 18.0,
          sale_price: 12.0,
          author: "Author 4",
          publisher: "Publisher 4",
          publication_date: "2021-04-01",
          pages: 150,
          language: "English",
          discounted_price: 12.0,
          weight: "400g",
          binding: "Paperback",
          dimensions: "19x13x1.5 cm",
        },
        {
          id: "5",
          name: "Reasoning Skills",
          images: ["https://radianbooks.in/Uploads/Products/quantative-aptitude-min-6513b32ba556b.webp"],
          price: 15.0,
          originalPrice: 20.0,
          discount: 25,
          rating: 4,
          sku_number: "SKU5",
          isbn_number: "ISBN5",
          title: "Reasoning Skills",
          base_price: 20.0,
          sale_price: 15.0,
          author: "Author 5",
          publisher: "Publisher 5",
          publication_date: "2021-05-01",
          pages: 180,
          language: "English",
          discounted_price: 15.0,
          weight: "450g",
          binding: "Paperback",
          dimensions: "20x14x2 cm",
        },
        {
          id: "6",
          name: "Quantitative Aptitude",
          images: ["https://radianbooks.in/Uploads/Products/general-intelligence-for-reasoning-2025-min-67a49a1da8c3e.webp"],
          price: 17.0,
          originalPrice: 22.0,
          discount: 20,
          rating: 5,
          sku_number: "SKU6",
          isbn_number: "ISBN6",
          title: "Quantitative Aptitude",
          base_price: 22.0,
          sale_price: 17.0,
          author: "Author 6",
          publisher: "Publisher 6",
          publication_date: "2021-06-01",
          pages: 220,
          language: "English",
          discounted_price: 17.0,
          weight: "500g",
          binding: "Paperback",
          dimensions: "21x15x2 cm",
        }
      ]
    }
  ];
  

  export const testimonials = [
    { id: "1", title: "Great Service!", youtubeUrl: "https://www.youtube.com/watch?v=vt2_XVNFCKQ" },
    { id: "2", title: "Highly Recommended!", youtubeUrl: "https://www.youtube.com/watch?v=JVe4GrAVBRU" },
  ];

  export const categoriesShopByState = ["UP", "Haryana", "Bihar", "Rajasthan", "MP", "Delhi", "Uttarakhand"]